### ISSUE TITLE
Keyboard Shortcut interference

### ISSUE THREAD

**Issue by ghost** [akfish/vscode-devdocs#1]
Keyboard shortcut conflict
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
{ "key": "shift+alt+d",           "command": "extension.downloadSettings", "when": "editorTextFocus" }

**Comment by akfish** [comment]
You could just assign custom keybindings to `devdocs.quickSearch` command. It is infeasible, if not impossible, to avoid keybinding conflict between any two random extensions.
