### ISSUE TITLE
Allow opening DevDocs without splitting the editor

### ISSUE THREAD

**Issue by volo-zyko** [akfish/vscode-devdocs#3]
Currently when pressing alt+shift+d devdocs splits the editor which is not very convenient to read on 15 inch screen. It would be good to make it configurable and either open a new tab or split the editor.

Another useful thing is to fix devdocs to one tab. I.e. instead of opening for each query a new tab always open docs in the same tab.

**Comment by holtalanm** [comment]
:+1:   I'm developing on a 13inch screen.  Splitting the editor is definitely not ideal.

**Comment by akfish** [comment]
Addressed by #7
